FROM debian:bookworm

RUN apt update -y && apt upgrade -y
RUN apt install -y gcc gdb valgrind

ARG DAY="01a"
ENV DAY=${DAY}

COPY . .

RUN as -gstabs -g day${DAY}.asm -o day${DAY}.o
RUN ld day${DAY}.o -o day${DAY}

ENTRYPOINT valgrind --tool=callgrind ./day${DAY} && callgrind_annotate --tree=both --inclusive=yes --auto=yes --show-percs=yes callgrind.out.7 > tree.7 && cp tree.7 /parent/callgrind.txt
