[package]
name = "aoc-2020"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
automod = "1.0"
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0"
