[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
automod = "1.0"
ndarray = "0.15"
nom = "7.1"
num-bigint = "0.4"
num-traits = "0.2"
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0"
